name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'   # har ghante me update karega
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Readme with GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
