name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # har ghante
  workflow_dispatch:      # manually run karne ka option

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          echo "![GitHub stats](https://github-readme-stats.vercel.app/api?username=AffafFarooq&show_icons=true&theme=radical)" > README.md

      - name: Commit changes
        run: |
          git config --global user.name "AffafFarooq"
          git config --global user.email "faffaf470@gmail.com"
          git add README.md
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
